### ISSUE TITLE
Warn user if ETL output data of a different format is in target directory

### ISSUE THREAD

**Issue by dogversioning** [smart-on-fhir/cumulus-etl#280]
I accidentally outputted some i2b2 ndjson into a deltalake folder and blew the data away by mistake. This, while uncommon, may be an error introduced by copying job scripts around.

It would be nice if, before running tasks, the etl checked to see if there was output data in that directory already, and warned a user if it would delete something that appeared to be a different etl output format.

**Comment by mikix** [comment]
Totes fair request - we should probably have the ndjson format class check the folder before deleting all existing contents.

It knows the pattern of filenames it writes - so if anything doesn't match that pattern, I'd say we should error out with a kind message.
