### ISSUE TITLE
include DATE in heading for import to labelstudio

### ISSUE THREAD

**Issue by comorbidity** [smart-on-fhir/cumulus-etl#298]
Please include DATE in the header for each section. 

For example

########################################
########################################
Neurosurgery Visit 
2024/03/12
########################################
########################################

**Comment by mikix** [comment]
Yeah that seems reasonable! A DocRef might not have the `date` field (though US Core does say it's a "must support" field, so hopefully it's filled out). But we can note that like `Unknown date` or something, for that rare case.

**Comment by mikix** [comment]
I don't think we currently sort the DocRefs either? We should probably sort by `date` too while we're inspecting that field.
