### ISSUE TITLE
Tech Debt: Resolve contextmanager-generator-missing-cleanup pylint warnings

### ISSUE THREAD

**Issue by dogversioning** [smart-on-fhir/cumulus-etl#313]
Relates to #312. This seemingly innocuous warning is stuborn to resolve while using nested generators - and the error is reported in the calling function, not the generator itself, though it could be in either - so for now we've just disabled it where it occurs.

Docs are at https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/contextmanager-generator-missing-cleanup.html - since this is fairly new behavior, perhaps there will be updates here?

**Comment by mikix** [comment]
This turned out to be a false positive in pylint
